Repository project-studying-dotnet/Streetcode-Server-December, pull requests merged in 2024-12, with the labels that each got.

#25 fix/19: remove unreachable condition
  Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlHandler.cs
Labels: bug

#31 test/SSAD-17/add_tests_for_MediatR_Email
  Streetcode/Streetcode.XUnitTest/MediatRTests/EmailTests/SendEmailHandlerTest.cs
Labels: test

#33 fix/18: Program class was moved into DbUpdate namespace
  Streetcode/DbUpdate/Program.cs
Labels: bug

#54 Test/ssad-35/add -tests-for-mediatr-media-audio
  Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/AudioTests/CreateAudioHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/AudioTests/DeleteAudioHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/AudioTests/GetAllAudiosHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/AudioTests/GetBaseAudioHandlerTests.cs
Labels: test

#95 Feat/90: implement Create part for Admin/Art gallery block
  .gitignore
  Streetcode/Streetcode.BLL/DTO/Media/Art/ArtCreateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/ArtDTO.cs
  Streetcode/Streetcode.BLL/DTO/Media/Art/StreetcodeArtDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Media/Images/ArtProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtHandler.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/ArtTests/CreateArtHandlerTests.cs
Labels: user story, task

#122 Test/119/write tests for fluentvalidation commands and queries
  Streetcode/Streetcode.BLL/Validation/Validators/CommandsAndQuerysValidators/CreateImageCommandValidator.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreateAudioCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreateImageCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreateInvoiceCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreatePartnerQueryValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreatePositionCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/CreateTeamLinkCommandValidatorTests.cs
  Streetcode/Streetcode.XUnitTest/ValidatorTests/SendEmailCommandValidatorTests.cs
Labels: test

#81 enhancment/68: implement global error handling middlware
  Streetcode/Streetcode.BLL/Exceptions/BadRequestException.cs
  Streetcode/Streetcode.BLL/Exceptions/ForbiddenAccessException.cs
  Streetcode/Streetcode.BLL/Exceptions/HttpException.cs
  Streetcode/Streetcode.BLL/Exceptions/InternalServerErrorException.cs
  Streetcode/Streetcode.BLL/Exceptions/NotFoundException.cs
  Streetcode/Streetcode.BLL/Exceptions/UnauthorizedAccessException.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Extensions/MiddlewareExtensions.cs
  Streetcode/Streetcode.WebApi/Middleware/GlobalExceptionHandlerMiddleware.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.XUnitTest/CustomMiddlewareTests/GlobalExceptionHandlerMiddlewareTests.cs
  Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
Labels: enhancement

#184 fix/176/add-logic-for-logging-error
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetByStreetcodeId/GetSubtitlesByStreetcodeIdHandler.cs
Labels: maintainability

#255 maintainbility/245/removed-unnecessary-cast-toList
  Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
Labels: maintainability

#261 Feat/260/add httpcontext extension method for appending tokens to cookies
  Streetcode/UserService.BLL/DTO/User/LoginResultDTO.cs
  Streetcode/UserService.BLL/DTO/User/UserDTO.cs
  Streetcode/UserService.BLL/Interfaces/User/IUserService.cs
  Streetcode/UserService.BLL/Mapping/User/UserProfile.cs
  Streetcode/UserService.BLL/Services/User/RegistrationService.cs
  Streetcode/UserService.WebApi/Controllers/UserController.cs
  Streetcode/UserService.WebApi/Extensions/HttpContextExtensions.cs
  Streetcode/UserService.WebApi/Program.cs
  Streetcode/UserService.XUnitTest/ControllerTests/UserControllerTests.cs
  Streetcode/UserService.XUnitTest/ExtensionsTests/HttpContextExtensionsTests.cs
  Streetcode/UserService.XUnitTest/ServicesTests/User/RegistrationServiceTest.cs
Labels: enhancement
